<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'js/app' => [
            'js' => [
                '/build/runtime.js',
                '/build/js/app.js',
            ],
        ],
    ],
],

]];
